apiVersion: v1
name: opendistro-elasticsearch
home: https://github.com/navikt/opendistro-elasticsearch
version: 0.5
description: Open Distro for Elasticsearch
sources:
  - https://github.com/navikt/opendistro-elasticsearch
maintainers:
  - name: Tuan Tran
    email: dinh.anh.tuan.tran@nav.no
