{{ if .Values.odfe.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.TEAM }}
spec:
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/pam-internal-search-api
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/pam-index
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/pam-er-sync
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/pam-search-api
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/pam-internalad-indexer
              - cluster.local/ns/{{ .Values.odfe.env.TEAM }}/sa/{{ template "fullname" . }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
{{ end }}
