{{ if .Values.odfe.generate_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-certs
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
type: Opaque
stringData:
  node.pem: |-
{{ .Files.Get ".secrets/node.pem" | indent 4 }}
  node-key.pem: |-
{{ .Files.Get ".secrets/node-key.pem" | indent 4 }}
  root-ca.pem: |-
{{ .Files.Get ".secrets/root-ca.pem" | indent 4 }}
  admin.pem: |-
{{ .Files.Get ".secrets/admin.pem" | indent 4 }}
  admin-key.pem: |-
{{ .Files.Get ".secrets/admin-key.pem" | indent 4 }}
  monitor.pem: |-
{{ .Files.Get ".secrets/monitor.pem" | indent 4 }}
  monitor-key.pem: |-
{{ .Files.Get ".secrets/monitor-key.pem" | indent 4 }}
{{ end }}
