apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "fullname" . }}-ingest-pdb
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    role: ingest
    team: {{ .Values.odfe.env.TEAM }}
spec:
  minAvailable: {{ sub .Values.ingest.replicas 1 }}
  selector:
    matchLabels:
      component: {{ template "fullname" . }}
      role: ingest
      team: {{ .Values.odfe.env.TEAM }}
