{{ if .Values.odfe.generate_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-certs
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
type: Opaque
stringData:
  node.pem: |-
{{ .Files.Get (printf ".secrets/%s/node.pem" .Values.env.cluster) | indent 4 }}
  node-key.pem: |-
{{ .Files.Get (printf ".secrets/%s/node-key.pem" .Values.env.cluster) | indent 4 }}
  root-ca.pem: |-
{{ .Files.Get (printf ".secrets/%s/root-ca.pem" .Values.env.cluster) | indent 4 }}
  admin.pem: |-
{{ .Files.Get (printf ".secrets/%s/admin.pem" .Values.env.cluster) | indent 4 }}
  admin-key.pem: |-
{{ .Files.Get (printf ".secrets/%s/admin-key.pem" .Values.env.cluster) | indent 4 }}
  monitor.pem: |-
{{ .Files.Get (printf ".secrets/%s/monitor.pem" .Values.env.cluster) | indent 4 }}
  monitor-key.pem: |-
{{ .Files.Get (printf ".secrets/%s/monitor-key.pem" .Values.env.cluster) | indent 4 }}
  gcs-key.json: |-
{{ .Files.Get (printf ".secrets/%s/gcs-key.json" .Values.env.cluster) | indent 4 }}
{{ end }}
