{{ if .Values.odfe.istio.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.TEAM }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: teampam
      - namespaceSelector:
          matchLabels:
            name: istio-system
        podSelector:
          matchLabels:
            app: prometheus
      - namespaceSelector:
          matchLabels:
            name: istio-system
        podSelector:
          matchLabels:
            istio: ingressgateway
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: istio-system
        podSelector:
          matchLabels:
            istio: istiod
      - namespaceSelector:
          matchLabels:
            name: istio-system
        podSelector:
          matchLabels:
            istio: pilot
      - namespaceSelector:
          matchLabels:
            name: istio-system
        podSelector:
          matchLabels:
            istio: mixer
      - namespaceSelector:
          matchLabels:
            name: istio-system
        podSelector:
          matchLabels:
            istio: ingressgateway
      - namespaceSelector:
          matchLabels:
            name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      - namespaceSelector:
          matchLabels:
            name: teampam
{{ end }}
