apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "fullname" . }}-master-pdb
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    role: master
    team: {{ .Values.odfe.env.TEAM }}
spec:
  minAvailable: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      component: {{ template "fullname" . }}
      role: master
      team: {{ .Values.odfe.env.TEAM }}
