{{- if .Values.ingress -}}
{{- $host := printf "%s.%s" (include "fullname" .) .Values.ingress.domain -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.TEAM }}
spec:
  rules:
    - host: {{ $host }}
      http:
        paths:
          - backend:
              serviceName: {{ template "fullname" . }}
              servicePort: 9200
            path: /
{{- end -}}
